name: Build ESP32

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Arduino
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32s3 main

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/
