name: Build ESP32

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile
      run: |
        arduino-cli compile \
        --fqbn esp32:esp32:esp32s3:FlashSize=8M,PartitionScheme=default \
        --build-property upload.maximum_size=3145728 \
        --output-dir build \
        --export-binaries \
        main

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/*.bin
